=== YuryKunitski/Task_1/src/equipment_res.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/equipments"
        xmlns:tns="http://www.example.com/equipments"
        elementFormDefault="qualified">


    <element name="equipments">
        <complexType>
            <choice maxOccurs="unbounded">
            <element ref="tns:KitchenEquipment"/>
            <element ref="tns:ViewingEquipment"/>
            <element ref="tns:Kettle"/>
            <element ref="tns:Microwave"/>
            <element ref="tns:MultiCooker"/>
            <element ref="tns:Computer"/>
            <element ref="tns:TV"/>
            </choice>
        </complexType>
    </element>

    <element name="KitchenEquipment" type="tns:KitchenEquipment"/>
    <element name="ViewingEquipment" type="tns:ViewingEquipment"/>
    <element name="Kettle" type="tns:Kettle"/>
    <element name="Microwave" type="tns:Microwave"/>
    <element name="MultiCooker" type="tns:MultiCooker"/>
    <element name="Computer" type="tns:Computer"/>
    <element name="TV" type="tns:TV"/>

    <complexType name="Equipment">
        <sequence>
            <element name="firmName" type="string"/>
            <element name="price" type="double"/>
            <element name="power" type="positiveInteger"/>
            <element name="working" type="boolean"/>
        </sequence>
    </complexType>

    <complexType name="KitchenEquipment">
        <complexContent>
            <extension base="tns:Equipment">
                <sequence>
                    <element name="volume" type="double"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <complexType name="ViewingEquipment">
        <complexContent>
            <extension base="tns:Equipment">
                <sequence>
                    <element name="sizeDisplay" type="positiveInteger"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

        <complexType name="Kettle">
            <complexContent>
                <extension base="tns:KitchenEquipment">
                    <sequence>
                        <element name="minWaterLevel" type="double"/>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>


    <complexType name="Microwave">
        <complexContent>
            <extension base="tns:KitchenEquipment">
                <sequence>
                    <element name="touchControl" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <complexType name="MultiCooker">
        <complexContent>
            <extension base="tns:KitchenEquipment">
                <sequence>
                    <element name="numbPrograms" type="positiveInteger"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Computer">
        <complexContent>
            <extension base="tns:ViewingEquipment">
                <sequence>
                    <element name="ram" type="positiveInteger"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="TV">
        <complexContent>
            <extension base="tns:ViewingEquipment">
                <sequence>
                    <element name="tvType">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="COSMOSTV"/>
                                <enumeration value="ZALA"/>
                                <enumeration value="VOKATV"/>
                                <enumeration value="BELTELECOM"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

</schema>

=== YuryKunitski/Task_1/src/equipment_res.xml
<?xml version="1.0" encoding="UTF-8"?>
<equipments xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://www.example.com/equipments"
            xsi:schemaLocation="http://www.example.com/equipments equipment_res.xsd">

    <Kettle>
        <firmName>Tefal</firmName>
        <price>50.0</price>
        <power>80</power>
        <working>true</working>
        <volume>1.8</volume>
        <minWaterLevel>0.3</minWaterLevel>
    </Kettle>

    <Microwave>
        <firmName>Atlant</firmName>
        <price>250.0</price>
        <power>1500</power>
        <working>false</working>
        <volume>17.5</volume>
        <touchControl>true</touchControl>
    </Microwave>

    <MultiCooker>
        <firmName>Tefal</firmName>
        <price>250.0</price>
        <power>1000</power>
        <working>true</working>
        <volume>8.0</volume>
        <numbPrograms>22</numbPrograms>
    </MultiCooker>

    <Computer>
        <firmName>LG</firmName>
        <price>1000.0</price>
        <power>500</power>
        <working>true</working>
        <sizeDisplay>22</sizeDisplay>
        <ram>1024</ram>
    </Computer>

    <Computer>
        <firmName>Aser</firmName>
        <price>500.0</price>
        <power>300</power>
        <working>true</working>
        <sizeDisplay>18</sizeDisplay>
        <ram>2048</ram>
    </Computer>

    <TV>
        <firmName>Sumsung</firmName>
        <price>1200.0</price>
        <power>800</power>
        <working>true</working>
        <sizeDisplay>52</sizeDisplay>
        <tvType>VOKATV</tvType>
    </TV>

    <TV>
        <firmName>Panasonic</firmName>
        <price>500.0</price>
        <power>400</power>
        <working>false</working>
        <sizeDisplay>32</sizeDisplay>
        <tvType>ZALA</tvType>
    </TV>

</equipments>
